### PR TITLE
PEP8 compliant code.

### PR DESCRIPTION
**Pull request by lewismc**
Hi folks, this makes the code PEP8 compliant. 
I am working on full blown documentation.

### CODE REVIEW

**Comment by RileyWilliams** [comment]
I cannot seem to get pycovjson to build correctly on travis, any ideas?

**Comment by lewismc** [comment]
Yes, I do have a suggestion. I would just run it against Python 3.5. Never mind the rest e.g. remove all other Python versions from .travis.yml. I would start there then we can work through improving the .travis.yml further.
Thanks

**Comment by lewismc** [comment]
The build is failing due to #13

**Review by RileyWilliams — APPROVED** [review]
Thanks!

**Pull request merged**
