### PR TITLE
ISSUE-42  unable to decode time units ... with the default calendar

### PR DESCRIPTION
**Pull request by lewismc**
This issue addresses #42 however in doing so we lessens the strictness of the conversion...
In the meantime, I've actually [reported the issue](https://podaac.jpl.nasa.gov/forum/viewtopic.php?f=7&t=847) with the input product over at PO.DAAC.

### CODE REVIEW

**Comment by RileyWilliams** [comment]
Hi @lewismc, maybe this should be an option which can be set using a command line flag?

**Comment by lewismc** [comment]
Hi @RileyWilliams I was also thinking we could implement a try catch scenario where the strict attempt (decode_times=True) is made first with an Exception being caught, handled and the reason being printed to standard out, then the less strict attempt (decode_times=False) being attempted.
Does this sound better?

**Comment by RileyWilliams** [comment]
@lewismc, yeah sounds good, as long as we are warning the user I think it's okay.

**Comment by RileyWilliams** [comment]
@lewismc, merged now, sorry it took so long!

**Pull request merged**
